version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo Installing dependencies for building Docker image

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - $(aws ecr get-login --no-include-email --region us-east-1)

  build:
    commands:
      - echo Building Docker image
      - docker build -t quickapp:latest .
      - echo Tagging Docker image
      - docker tag quickapp:latest 590183799919.dkr.ecr.us-east-1.amazonaws.com/quickapp:latest

  post_build:
    commands:
      - echo Pushing Docker image to ECR
      - docker push 590183799919.dkr.ecr.us-east-1.amazonaws.com/quickapp:latest
