AWSTemplateFormatVersion: "2010-09-09"
Description: Quick App Secrets Manager secrets with placeholders for key/value pairs.

Resources:
  QuickAppDevelopmentSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: quickapp/appsettings.Development.json
      Description: "quickapp/appsettings.Development.json"
      SecretString: '
        {
        "rds_url": "url",
        "rds_username": "MasterUsername",
        "rds_password": "secret-password",
        "spring_mail_protocol": "smtp",
        "spring_mail_host": "smtp.gmail.com",
        "spring_mail_port": 465,
        "spring_mail_username": "rentxmailservice@gmail.com",
        "spring_mail_password": "kjxvsktjrrddotof",
        "spring_mail_properties_mail_smtp_auth": true,
        "spring_mail_properties_mail_smtp_starttls_enable": true,
        "mail_smtp_starttls_enable": false,
        "spring_mail_properties_mail_smtp_ssl_enable": true,
        "spring_mail_properties_mail_smtp_starttls_required": true,
        "allowed_origin": "http://localhost:8080",
        "system_email": "rentxmailservice@gmail.com"
        }'
      Tags:
        - Key: AppName
          Value: QuickApp

  QuickAppSecret:
    Type: "AWS::SecretsManager::Secret"
    Properties:
      Name: quickapp/appsettings.json
      Description: "quickapp/appsettings.json"
      SecretString: '
        {
        "rds_url": "url",
        "rds_username": "MasterUsername",
        "rds_password": "secret-password",
        "spring_mail_protocol": "smtp",
        "spring_mail_host": "smtp.gmail.com",
        "spring_mail_port": 465,
        "spring_mail_username": "rentxmailservice@gmail.com",
        "spring_mail_password": "kjxvsktjrrddotof",
        "spring_mail_properties_mail_smtp_auth": true,
        "spring_mail_properties_mail_smtp_starttls_enable": true,
        "mail_smtp_starttls_enable": false,
        "spring_mail_properties_mail_smtp_ssl_enable": true,
        "spring_mail_properties_mail_smtp_starttls_required": true,
        "allowed_origin": "http://localhost:8080",
        "system_email": "rentxmailservice@gmail.com"
        }'
      Tags:
        - Key: AppName
          Value: QuickApp

Outputs:
  QuickAppDevelopmentSecretArn:
    Description: "ARN of the created development secret"
    Value: !Ref QuickAppDevelopmentSecret
    Export:
      Name: !Sub "${AWS::StackName}-DevelopmentSecretArn"

  QuickAppDevelopmentSecretName:
    Description: "Name of the created development secret"
    Value: !Ref QuickAppDevelopmentSecret
    Export:
      Name: !Sub "${AWS::StackName}-DevelopmentSecretName"

  QuickAppSecretArn:
    Description: "ARN of the created secret"
    Value: !Ref QuickAppSecret
    Export:
      Name: !Sub "${AWS::StackName}-SecretArn"

  QuickAppSecretName:
    Description: "Name of the created secret"
    Value: !Ref QuickAppSecret
    Export:
      Name: !Sub "${AWS::StackName}-SecretName"
